application: sony-pmca
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: webapp2
  version: latest

skip_files:
- ^build$
- ^dist$
- ^updatershell$

handlers:
- url: /(robots\.txt)
  static_files: \1
  upload: robots\.txt
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /camera/xpd/.+
  script: main.app
  secure: optional
- url: /cleanup
  login: admin
  auth_fail_action: unauthorized
  script: main.app
  secure: always
- url: /.*
  script: main.app
  secure: always
